sudo: false
git:
  depth: 3
branches:
  only:
  - master
  - travis
  - "/^feature/.*$/"
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
  - "/^deploy-.*$/"
  - "/^GH-.*$/"
language: node_js
node_js:
- node
cache:
  directories:
  - "$HOME/.npm"
  - node_modules
install:
- npm install
before_script:
- npm install -g gulp-cli
script: gulp
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: app
    on:
      branch: master
  - provider: npm
    email: ingo.reinhart@chefkoch.de
    api_key:
      secure: "$NPMJS_TOKEN"
    on:
      tags: true
      repo: chefkoch-dev/design-system
