sudo: false

### Git cloning and build trigger config ###

git:
  depth: 3

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^deploy-.*$/



### Environment ###

language: node_js
node_js:
  - "node"

cache:
  directories:
  - $HOME/.npm
  - "node_modules"


### Installing dependencies ###

install:
  - npm install


### Build ###

before_script:
  - npm install -g gulp-cli

script: gulp



### Deployment ###

deploy:
  #### Deploy the Static Design System to Github Pages / design.chefkoch.de ####
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: components/app/web
  on:
    branch: master


### Notifications ###

notifications:
  hipchat:
    rooms:
      - $HIPCHAT_TOKEN@HIPCHAT_ROOM_ID
    notify: true
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'